language: c
sudo: false
dist: xenial

addons:
  apt:
    packages:
      - lua5.1
      - lua5.2
      - lua5.3

env:
  - LUA_VERSION=5.3
  - LUA_VERSION=5.2
  - LUA_VERSION=5.1

script: 
  - lua$LUA_VERSION hsluv_test.lua